name: cortex-semantic-model-generator
channels:
  - conda-forge
  - snowflake
  - defaults
dependencies:
  - python>=3.10,<3.12
  - pandas>=2.2.0
  - tqdm>=4.66.0
  - streamlit>=1.35.0
  - loguru>=0.5.3
  - protobuf>=3.20.0,<4.0.0
  - pydantic>=2.8.0
  - pyyaml>=6.0.0
  - ruamel.yaml>=0.17.0
  - pyarrow>=13.0.0,<15.0.0
  - sqlglot>=25.0.0
  - numpy>=1.26.0
  - python-dotenv>=0.21.0
  - urllib3>=2.2.0
  - requests>=2.32.0
  - types-pyyaml>=6.0.0
  - types-protobuf>=4.25.0
  - snowflake-snowpark-python>=1.18.0
  - streamlit-extras>=0.4.0
  - cattrs>=23.1.0